require "user.options"
require "user.plugins"
require "user.keymaps"
require "user.mason"
require "user.colorscheme"
require "user.lsp"
require "user.snippets"
require "user.cmp"
require "user.telescope"
require "user.treesitter"
require "user.dap"
require "user.autopairs"
--require "user.comment"
require "user.whichkey"
require "user.slime"
require "user.symbolsoutline"
require "user.vimtex"
require "user.obsidian"


vim.filetype.add({extension = {typ = 'typst'}})
